### ISSUE TITLE
Compiler warnings.

### ISSUE THREAD

**Issue by bbilonog** [jwplayer/JWPlayer-iOS-SDK-cocoapod#1]
Good morning, or afternoon, or evening, depending on where you are :]

After installed JWPlayer via Cocoapods I got compiler warnings.

<img width="954" alt="screen shot 2016-02-11 at 9 52 25 am" src="https://cloud.githubusercontent.com/assets/14905005/12971642/0bbac160-d0a6-11e5-8dff-5f05f3e4fc77.png">

Thanks!

**Comment by MaxMikheyenko** [comment]
Hi, we're aware of these warnings, plan to get rid of them in 2.2.0. thanks.
