### ISSUE TITLE
Resize control bar

### ISSUE THREAD

**Issue by kilirushi** [jwplayer/JWPlayer-iOS-SDK-cocoapod#10]
I have problem with control bar when I resize view player and the control bar was hidden.
Please watch video below help me:
[JW_ControlBar.zip](https://github.com/jwplayer/JWPlayer-iOS-SDK-cocoapod/files/908285/JW_ControlBar.zip)
Please help me resolve this.

**Comment by kilirushi** [comment]
And I have problem when I'm click full screen video with my device mode portrait then I'm exit full screen then JWPlayerView was rotation landscape. How to keep view not rotation when I exit mode fullscreen?.

**Comment by karimJWP** [comment]
@kilirushi thank you for sharing the video. Is the issue that you cannot click the controls ? Could you please email support+sdk@jwplayer.com with a demo app to reproduce ? we cannot reproduce on our end
With regards to view not rotating, when exiting fullscreen, it could be that your viewController's supported interface is set to portrait. If you contact support+sdk@jwplayer.com they will give you a vanilla demo app which you can augment to show us your use case.
