### ISSUE TITLE
Bug in JWFullScreenViewController 

### ISSUE THREAD

**Issue by vandyshev** [jwplayer/JWPlayer-iOS-SDK-cocoapod#12]
http://crashes.to/s/470002a8721

**Comment by karimJWP** [comment]
a safeguard was introduced in version 2.7.9, released today to prevent this crash

**Comment by karimJWP** [comment]
@sethsamuel please contact support+sdk@jwplayer.com, they will be able to get the necessary information from you to reproduce the issue on our end. Once we can reproduce, we will work on a fix
