### ISSUE TITLE
[UIApplication statusBarOrientation] must be used from main thread only

### ISSUE THREAD

**Issue by ashishfission** [jwplayer/JWPlayer-iOS-SDK-cocoapod#14]
file:///var/lib/jenkinsosx/workspace/s-sdk-ci-cd-pipeline_master-D4PERWRCZBQ4SARRHREJU6HJMPGUU53LVN4JF3RWE2NG6SVK5CYQ/SDK/JWPlayer-iOS-SDK/Components/JWRotationHandler.m: runtime: UI API called from background thread: -[UIApplication statusBarOrientation] must be used from main thread only
<img width="520" alt="screen shot 2017-09-27 at 11 13 11 pm" src="https://user-images.githubusercontent.com/1861018/30928563-93338390-a3d9-11e7-8a64-dd84d763d742.png">

**Comment by karimJWP** [comment]
fixed in version 2.7.9, released today :)
