### ISSUE TITLE
Ads with timeOffset="start" are not reliably shown

### ISSUE THREAD

**Issue by Kymer** [jwplayer/JWPlayer-iOS-SDK-cocoapod#16]
A few days ago I created [an issue on the _jwplayer-sdk-ios-demo_ repo](https://github.com/jwplayer/jwplayer-sdk-ios-demo/issues/34). I now realise *this* repo might more relevant and better suited for this issue.

### Expected Behavior

'Preroll ads' with a `timeOffset` set to `"start"` are shown consistently.

### Actual Behavior

With the latest JWPlayer SDKs, preroll ads are sometimes not shown and the player is in a weird state where the *actual video content* starts playing instead of the ad. Skipping the 'ad' will start playing the content normally. 

![preroll-not-shown](https://user-images.githubusercontent.com/9093854/33872111-c8cad086-df15-11e7-8fb5-17fcca7da606.png)

### Steps to reproduce

This can be reproduced on iOS devices running iOS 10 or 11 with the following [vmap XML](https://gist.github.com/Kymer/a09eecaece492ad2409b2565a087067c) (this is de VMAP used for the web player on the demo page of JWPlayer). On iOS 9 the prerolls seem to be reliably shown.

### Environment

- iPhone, iPad (any)
- iOS 10, iOS 11
- JWPlayer-SDK version 2.7.10, 2.7.11

**Comment by okulagin** [comment]
@Kymer just FYI that this issue is in our backlog, but no ETA yet
