### ISSUE TITLE
App Rejected - Use of non public Pegasus Framework - PGHostedWindow

### ISSUE THREAD

**Issue by modecolems** [jwplayer/JWPlayer-iOS-SDK-cocoapod#18]
Hi, 

Our Application have just been rejected because your SDK is using/referencing a non-public API (PGHostedWindows from Pegasus.framework) which is forbidden by the Guideline 2.5.1

I'm using the last stable version : 2.6.8

I tried to update to the lastest version 2.8.3, but I cannot export archive because bitcode problem (I've seen an issue about that).

This is very annoying regarding to the price we had to pay, since your new licence, to be able to use this library !!!

**Comment by okulagin** [comment]
Hi @modecolems ,

As far as for bitcode issue - it is fixed in 2.8.4 which has been just released. As far as for non-public API I'll get back to you later.

**Comment by modecolems** [comment]
Hi thx for the fast update. I've just tested it and it seems that PGHostedWindows is not used anymore in this version.

I think you should remove the indication last stable of the 2.6.8 version on the JWPlayer Website since app could be rejected.

Regards.

**Comment by okulagin** [comment]
@modecolems you are welcome! In case you have any issues please contact the JWP support.

**Comment by alicanozkara** [comment]
i have same problem. have this problem been resolved with the 2.8.5 version?

**Comment by modecolems** [comment]
@alicanozkara 
Our apps has been accepted with the 2.8.4 version telling that the non-public api came from the JWPlayer Library.

**Comment by alicanozkara** [comment]
@modecolems thank you for answer.

**Comment by okulagin** [comment]
Hi there,

Just would like to let you know that our team right now is working on cleaning SDK from any private api. ETA is 2 weeks.

**Comment by maxhalty** [comment]
We are having the same problem over here. We hope you find a solution because we need to launch our app ASAP.

**Comment by okulagin** [comment]
@maxhalty  we are releasing a patch today. It is going to be 2.8.6

**Comment by okulagin** [comment]
The new version is available. Please see the release notes: https://developer.jwplayer.com/sdk/ios/docs/developer-guide/about/release-notes/

**Comment by tanujtak1986** [comment]
Hi.

**Comment by robonaut** [comment]
@tanujtak1986 

Try `#import` <JWPLayer_iOS_SDK/JWPlayerController.h>` instead and see if that works?

**Comment by maxhalty** [comment]
Everything is working now and Apple approved the new version of my app, thanks!

**Comment by Saj1234** [comment]
#import <JWPLayer_iOS_SDK/JWPlayerController.h> fixed the issue of file not found issue. for me. Would be great if you can update the documentation. Wasted lot of time on this after updating.

**Comment by okulagin** [comment]
@Saj1234 thanks for the suggestion. Will do.
