### ISSUE TITLE
User's interactions lost on fullscreen and device roation

### ISSUE THREAD

**Issue by yanndupuy** [jwplayer/JWPlayer-iOS-SDK-cocoapod#19]
In fullscreen mode when we rotate the main UIView container of the class 'JWFullScreenViewController' is resize we a bad and become very tiny. So UI interface and your UIWebView is outside the main UIView bounds. It's also the case for a UIView which is add on our controller which call the player.

We have reference on object 'JWFullScreenViewController' however for fix this issue we find the following trick for resize all bad elements.

`
- (void)jwPlayerLayoutFix
{
    for (UIWindow * aWindow in [UIApplication sharedApplication].windows)
    {
#ifdef DEBUG
        //NSLog(@"Window debug : %@",aWindow.debugDescription);
        //NSLog(@"\n\nTEST root : %@\n\n\n\n",aWindow.rootViewController.debugDescription);
#endif
        NSString *strClass = NSStringFromClass([aWindow.rootViewController class]);
        
        if ([strClass isEqualToString:@"JWFullScreenViewController"])
        {
            // Fix main View layout in JWPlayer window instance, masterview of class 'JWFullScreenViewController'
            aWindow.rootViewController.view.frame = [UIScreen mainScreen].bounds;
        }
    }
    
    // Fix Layout on view added on our masterView by JWPlayer
    UIView *jwInteractionView =  (UIView*)self.view.subviews[0];
    
    //[jwInteractionView removeConstraints:jwInteractionView.constraints];
    jwInteractionView.frame = self.playerController.view.frame;
    
#ifdef DEBUG
    //NSLog(@"jwInteractionView : %@",jwInteractionView.debugDescription);
#endif
}
`

Regards

**Comment by yanndupuy** [comment]
issue still present in v2.8.6

**Comment by louiskane** [comment]
I got same issue .

**Comment by karimMourra** [comment]
Hi @yanndupuy sorry for the late reply. Since your last comment we have done multiple improvements in our SDK. Today we release version 3.6.1. Please let us know if your issue persists and we will get back to you promptly. Cheers!
