### ISSUE TITLE
Calling seek(position: Int) on JWPlayerController while it is still buffering causes the player to show "Live Broadcast"

### ISSUE THREAD

**Issue by collinsmwade** [jwplayer/JWPlayer-iOS-SDK-cocoapod#20]
![img_6e666400e084-2](https://user-images.githubusercontent.com/3690795/36810801-71f75310-1c91-11e8-8f66-fb55dc729de7.jpeg)

Title says it all. My JWPlayerDelegate seeks the playerController when onReady() is called by the playerController. This seems to confuse the JWPlayerController into thinking that it is streaming a live broadcast. 

I might be calling seek in the wrong place, but if I wait any longer, the player flashes the first couple frames of the video before the seek is called. I would really just like a way to start playing a video at a specific position. Thank you

**Comment by karimMourra** [comment]
Hi @collinsmwade ! Since your last comment we have made multiple improvements to our SDK. Today we release version 3.6.1. Please let us know if your issue persists and we will get back to you promptly. Cheers and happy coding !
