### ISSUE TITLE
Changing video quality while a seek is in progress wipes out the seek

### ISSUE THREAD

**Issue by collinsmwade** [jwplayer/JWPlayer-iOS-SDK-cocoapod#21]
Title says it all. If I call seek on a JWPlayerController, then change the quality while that seek is loading, the seek doesn't happen anymore. 
This is especially crucial when I'm first starting the player, because I want to start the video where the user left off.

**Comment by karimMourra** [comment]
Hi @collinsmwade in an effort to increase our response times we will be closing the issues section in this repo. If this is still an issue please reopen this issue in https://github.com/jwplayer/jwplayer-ios-bestPracticeApps
