### ISSUE TITLE
Unable to upload to AppStore. Errors: ITMS-90087, ITMS-90635, ITMS-90208, ITMS-90125

### ISSUE THREAD

**Issue by wieweb** [jwplayer/JWPlayer-iOS-SDK-cocoapod#22]
Hi,
I was rejected by Apple cause of using private API see: [https://github.com/jwplayer/JWPlayer-iOS-SDK-cocoapod/issues/18](https://github.com/jwplayer/JWPlayer-iOS-SDK-cocoapod/issues/18)

Now I updated to the latest Version (2.8.6+44) of JWPlayer and I get a bunch of errors during AppStore upload process. Errors: ITMS-90087, ITMS-90635, ITMS-90208, ITMS-90125
See screenshot:
![screen shot 2018-03-08 at 15 59 49](https://user-images.githubusercontent.com/5238441/37158725-5bb5cf26-22ec-11e8-9e9d-25b3ec80ec39.jpg)

I'm using the latest Xcode, swift 4, bitcode enabled, iOS application for iPhone and iPad.

**Comment by davidmedaxion** [comment]
Did you ever receive a response to this?  We're getting the same errors using ver 2.8.9

**Comment by wieweb** [comment]
Sorry I did not got any response from JWPlayer.

**Comment by songxiaoliang** [comment]
@wieweb I also encountered the same problem, I do not know how to solve

**Comment by coderDove** [comment]
Dear developers, 
@songxiaoliang @wieweb @davidmedaxion have you extruded simulator architectures from JWPPlayer_iOS_SDK ? In JWPlayer iOS SDK manual at https://developer.jwplayer.com/sdk/ios/docs/developer-guide/troubleshooting/migration/ there is a link on how it should be done. As Cocoapods requires to include all architectures for distribution but Apple requires x86_64 and i386 targets to be removed prior to submitting the app to the App Store you need to make additional step of removing simulator architectures from SDK. To remove simulator architecture you need to navigate inside JWPlayer_iOS_SDK.framework package in Terminal and to execute next commands:

```
lipo -remove i386 JWPlayer_iOS_SDK -o JWPlayer_iOS_SDK 
lipo -remove x86_64 JWPlayer_iOS_SDK -o JWPlayer_iOS_SDK
```

To verify that no simulator architectures are present you can executed next command:
`lipo -info JWPlayer_iOS_SDK`

As a result you should see only arm architectures present inside JWPlayer_iOS_SDK.framework.
After that you can submit application to AppStore.

Please let us know of this helps.

Kind regards,
JWPlayer Team

**Comment by songxiaoliang** [comment]
@coderDove yeah，thanks. I will take a moment to try out whether this solution can be solved. Thank you very much. Do you have WeChat? I can keep in touch with you soon~

**Comment by coderDove** [comment]
@songxiaoliang , hope this will help.
I am kindly ask you to provide your feedback on this solution within this ticket - to make at visible for other guys and to close an issue if it works.
Thank you.

**Comment by songxiaoliang** [comment]
Has been resolved, the method is as follows:
(1) Open Build Phasse: Add Run Script
(2) Paste the following command into it：
-----------------------------------------------------------------------------------------
APP_PATH="${TARGET_BUILD_DIR}/${WRAPPER_NAME}"  
  
find "$APP_PATH" -name '*.framework' -type d | while read -r FRAMEWORK  
do  
FRAMEWORK_EXECUTABLE_NAME=$(defaults read "$FRAMEWORK/Info.plist" CFBundleExecutable)  
FRAMEWORK_EXECUTABLE_PATH="$FRAMEWORK/$FRAMEWORK_EXECUTABLE_NAME"  
echo "Executable is $FRAMEWORK_EXECUTABLE_PATH"  
  
EXTRACTED_ARCHS=()  
  
for ARCH in $ARCHS  
do  
echo "Extracting $ARCH from $FRAMEWORK_EXECUTABLE_NAME"  
lipo -extract "$ARCH" "$FRAMEWORK_EXECUTABLE_PATH" -o "$FRAMEWORK_EXECUTABLE_PATH-$ARCH"  
EXTRACTED_ARCHS+=("$FRAMEWORK_EXECUTABLE_PATH-$ARCH")  
done  
  
echo "Merging extracted architectures: ${ARCHS}"  
lipo -o "$FRAMEWORK_EXECUTABLE_PATH-merged" -create "${EXTRACTED_ARCHS[@]}"  
rm "${EXTRACTED_ARCHS[@]}"  
  
echo "Replacing original executable with thinned version"  
rm "$FRAMEWORK_EXECUTABLE_PATH"  
mv "$FRAMEWORK_EXECUTABLE_PATH-merged" "$FRAMEWORK_EXECUTABLE_PATH"  
  
done
-----------------------------------------------------------------------------------------
(3) Rebuild
