### ISSUE TITLE
Cannot use JWPlayer-SDK  on swift project

### ISSUE THREAD

**Issue by Dekablade01** [jwplayer/JWPlayer-iOS-SDK-cocoapod#25]
Swift project cannot find JWPlayer SDK, cause no `SWIFT_OBJC_BRIDGING_HEADER`

**Comment by cjcolej** [comment]
They are expecting you to create your own bridging header. Here was my solution:

 - Add JWPlayer pod to Podfile `pod 'JWPlayer-SDK'`

 - (optional) Create a folder in the main project directory called `Headers`.

 - Create a file called `JWPlayer-Bridging-Header.h` inside that folder

 - Add the following code to the file:

```
#ifndef JWPlayer_Bridging_Header_h
#define JWPlayer_Bridging_Header_h

#import "JWPlayer-SDK/JWPlayer_iOS_SDK.framework/Headers/JWPlayerController.h"

#endif
```

 - Click on your project target in xcode and go to `Build Settings` at the top

 - Search for `User Header Search Paths` in the search box

 - Change the value to `${PODS_ROOT}`

 - Search for another property called `Objective-C Bridging Header`

 - Add this path to that property (replace with the name of your project directory and ensure that it is the path to the bridging header file) `project-dir/Headers/JWPlayer-Bridging-Header.h`

 - Run `pod install` in the terminal

 - Build the project!
