### ISSUE TITLE
Controls hiding is not working

### ISSUE THREAD

**Issue by arvindsen14** [jwplayer/JWPlayer-iOS-SDK-cocoapod#28]
Hi,
Controls hiding is not working when I set "config.controls = false".
Also can we hide next button option in controls.

Please do needful.

Best,
Arvind

**Comment by karimMourra** [comment]
Hi! @arvindsen14 Apologies for the late response, please reopen if your issue is persisting. Since your last comment, we have made many improvements to our SDK.
