### ISSUE TITLE
2.3.0 does not support bitcode

### ISSUE THREAD

**Issue by KristopherGBaker** [jwplayer/JWPlayer-iOS-SDK-cocoapod#3]
I recently added JWPlayer to the project I'm working on.  It was working and building fine with 2.2.1, but with the 2.3.0 release, I'm seeing the following error.

ld: bitcode bundle could not be generated because '.../Pods/JWPlayer-SDK/libJWPlayer-iOS-SDK.a(JWRuntimeCreator.o)' was built without full bitcode. All object files and libraries for bitcode must be generated from Xcode Archive or Install build for architecture armv7

**Comment by MaxMikheyenko** [comment]
should be fixed in 2.3.1

**Comment by KristopherGBaker** [comment]
2.3.1 works for me.  Thanks.
