### ISSUE TITLE
App in Background disconnect chromecast device by closing socket

### ISSUE THREAD

**Issue by iris112** [jwplayer/JWPlayer-iOS-SDK-cocoapod#31]
Hello.
My name is Filip
Thanks for your helpful source.
I'm using this to integrate and expand our project for casting media.
But i'm getting trouble with some issues.

- First, When the app goes into background, the google cast sdk close the socket, so my iphone disconnected from cast device.

> I need to keep the session and not disconnect.

- Second, when i disconnected from device, i retry to connect manually, but i'm getting the following errors.

> [GCKDeviceAuthChannel timerDidFire:] authentication timed out
> [GCKCastDeviceConnector deviceAuthChannel:didFailToAuthenticateWithError:] Not an authentic device, disconnecting.
> Error Domain=com.google.GCKError Code=3 "Device authentication failure" UserInfo={NSLocalizedDescription=Device authentication failure}

I don't understand why is that. When i try to connect first, there is no authentication error, but i retry to connect secondly, i'm getting authentication error.

Please help me.
This is urgen issue for our project.

Thanks.
Regards.

**Comment by karimMourra** [comment]
hi @iris112 in an effort to increase our response times we will be closing the issues section in this repo. If this is still an issue please reopen this issue in https://github.com/jwplayer/jwplayer-ios-bestPracticeApps

**Comment by karimMourra** [comment]
@iris112 the Google Cast SDK doesn't allow casting when the app is backgrounded. That is the default behavior
