### ISSUE TITLE
Add `static_framework = true` to Podspec

### ISSUE THREAD

**Issue by mbanasiewicz** [jwplayer/JWPlayer-iOS-SDK-cocoapod#32]
Otherwise, it's not possible to import JWPlayer into dynamic swift framework

**Comment by karimMourra** [comment]
hi @mbanasiewicz in an effort to increase our response times we will be closing the issues section in this repo. If this is still an issue please reopen this issue in https://github.com/jwplayer/jwplayer-ios-bestPracticeApps
