### ISSUE TITLE
Resume Playback Swift 4.2

### ISSUE THREAD

**Issue by JakfarShodiq** [jwplayer/JWPlayer-iOS-SDK-cocoapod#36]
Hi Guys, My company using this player for paid. And me as a developer set up the player. How I can resume playback when I played with the same video?

I using swift 4.2

Need help, please

Thanks a lot

**Comment by karimMourra** [comment]
Hi it seems like your issue may be specific to your implementation. Could you please contact support+sdk@jwplayer.com, they will obtain the necessary information from you required to reproduce your issue.

**Comment by JakfarShodiq** [comment]
Hi bro @karimMourra, thank u for your advice. I already sent the email to them.
Here maybe others can help hehe

**Comment by karimMourra** [comment]
got it! Are you using vpaid ads ? Could you share streams and reproduction steps ?

**Comment by JakfarShodiq** [comment]
Hi man @karimMourra , Already answered by jwplayer support team, and I do implement with my current code.

**Comment by karimMourra** [comment]
Great to know!
