### ISSUE TITLE
AirPlay not working in iOS 12

### ISSUE THREAD

**Issue by matheusfalcao20** [jwplayer/JWPlayer-iOS-SDK-cocoapod#38]
I am trying to connect my application with JWPlayer in AirPlay, however it is giving the following error in console:

`AVAudioSessionPortImpl.mm:56:ValidateRequiredFields: Unknown selected data source for Port Alto-falante (type: Speaker)`
`AVAudioSessionPortImpl.mm:56:ValidateRequiredFields: Unknown selected data source for Port AirPlay (type: AirPlay)`

And never connect with Apple TV.

iPhone Xr - iOS 12.1.4
Xcode 10.2.1
Swift 4.2

My code:

       do {
            try AVAudioSession.sharedInstance().setCategory(.playback, options: .allowAirPlay)
            try AVAudioSession.sharedInstance().setActive(true)
        } catch {
            print(error)
        }

And:

            self.airPlayView = MPVolumeView(frame: CGRect(x: self.videoView.bounds.size.width - 5 - airPlayButtonWidth, y: 0, width: airPlayButtonWidth, height: airPlayButtonWidth))
            self.airPlayView.showsVolumeSlider = false
            self.airPlayView.backgroundColor = UIColor.backgroundOntt.withAlphaComponent(0.2)
            self.airPlayView.autoresizingMask = UIView.AutoresizingMask.flexibleLeftMargin

            self.player.view.addSubview(self.airPlayView)

Thanks

**Comment by karimMourra** [comment]
@matheusfalcao20 thank you for reporting this issue. Does the airPlay button ever appear ? Are you able to select your airPlay device ? Does anything happen on the screen? We will attempt to reproduce in our office; do you have the url of the stream you are trying to cast ?

**Comment by matheusfalcao20** [comment]
The AirPlay button appears and I can select my device. Then the Apple TV screen starts to blink

**Comment by karimMourra** [comment]
Oi @matheusfalcao20 in an effort to increase our response times we will be closing the issues section in this repo. If this is still an issue please reopen this issue in https://github.com/jwplayer/jwplayer-ios-bestPracticeApps
