### ISSUE TITLE
Video is not loading when calling seek() inside onBeforePlay()

### ISSUE THREAD

**Issue by rkyslyy** [jwplayer/JWPlayer-iOS-SDK-cocoapod#39]
I want video to start from a specific position. For that I call `seek()` inside of `onBeforePlay()` method. But after that video in just infinitely loading, no matter what position I click afterwards:
<img src="https://user-images.githubusercontent.com/33093275/59762601-41ed3c80-92a0-11e9-86e9-26671547148b.png" width="40%">

I have also tried to call `seek()` inside of `onPlayAttempt()`. Video starts playing on a correct position, but slider never moves and `player.position` is never updated, it's always `0.0`:
<img src="https://user-images.githubusercontent.com/33093275/59762952-1159d280-92a1-11e9-8ff7-a041730a1803.png" width="40%">

Calling `seek()` from inside of `onPlay()` kinda does the trick, but player has time to show the beginning of a video for a short time and only after that position is changed and player starts to load correct video moment, which is not ideal.

**Comment by karimMourra** [comment]
Hi @rkyslyy sorry for the late response. We introduced a `startTime` property on the  `JWPlaylistItem`  which  will allow you to achieve your desired behavior.

An update  on this repo: in an effort to increase our response times we will be closing the issues section in this repo. If this is still an issue please reopen this issue in https://github.com/jwplayer/jwplayer-ios-bestPracticeApps
