### ISSUE TITLE
Private API is used

### ISSUE THREAD

**Issue by greis** [jwplayer/JWPlayer-iOS-SDK-cocoapod#4]
Apple is rejecting our binary saying that the private API `ad` is being used on the following methods:

- [JWGoogimaPlaylistHandler adScheduleFromJSON:]
- [JWConfigDataConverter dictionaryRepresentationForAdSchedule:]

Are you aware of this?

**Comment by karimJWP** [comment]
Hi Gabriel, this issue was fixed on version 2.5.3
Could you please update to the latest version and confirm ?

**Comment by greis** [comment]
They approved our app with the version 2.5.3. Thanks!
