### ISSUE TITLE
Fatal Exception: NSInvalidArgumentException

### ISSUE THREAD

**Issue by breahna-ebs** [jwplayer/JWPlayer-iOS-SDK-cocoapod#40]
We encounter a lot of crashes in crashlytics on this issue:
![Screen Shot 2019-07-01 at 1 44 38 PM](https://user-images.githubusercontent.com/36886797/60434276-743b5a00-9c0f-11e9-832e-1683c9653363.png)

We use library version `JWPlayer-SDK (3.5.1)`

Can you help understand the issue?

**Comment by AmitaiB** [comment]
Besides observing that something is trying to call an NSString method with a `nil` argument (which [produces the exception](https://developer.apple.com/documentation/foundation/nsstring?language=objc#dash_1412307) as reported above), there is not much that can be said devoid of context. With a question this specific, your best bet is to prepare a demo app with reproduction steps and file a ticket with JW Support from your JWPlayer dashboard.
cc: @karimMourra

**Comment by karimMourra** [comment]
@AmitaiB agreed. 
@breahna-ebs could you please share your config? Are you using ads by any chance ?

**Comment by breahna-ebs** [comment]
@karimMourra Yes. We are using ads. 
I'll try to make a demo and see if I can reproduce it.

**Comment by karimMourra** [comment]
Hi @breahna-ebs any updates ?

**Comment by breahna-ebs** [comment]
@karimMourra We couldn't reproduce the issue yet. But we still keep it receiving it in crashlytics. 
I'll close the issue for now and will get back as soon as we get more details.

**Comment by vinayakparmar92** [comment]
Even we are facing a lot of crashes with the exact same crash logs. Any update on this @breahna-ebs ?

**Comment by karimMourra** [comment]
@vinayakparmar92 and @breahna-ebs we will be attempting to address this for 3.7.0 . We cannot guarantee the fix will work since we do not have reproduction steps, but we will do our best.

**Comment by vinayakparmar92** [comment]
When are you guys planning to release that version out?

**Comment by AmitaiB** [comment]
@vinayakparmar92 It's _targeted_ for early October.

**Comment by AmitaiB** [comment]
@vinayakparmar92 and @breahna-ebs and others checking up on this issue -- we have been getting corroborating reports a month after going live that this crash was indeed resolved in 3.7.0.

**Comment by breahna-ebs** [comment]
@AmitaiB I missed the release. Will update the library. Thanks!
