### ISSUE TITLE
Add volume slider

### ISSUE THREAD

**Issue by colin1994** [jwplayer/JWPlayer-iOS-SDK-cocoapod#41]
I want to know if I can add volume slider on iOS, which is consistent with the performance on the web side. As shown below:

![volume_slider](https://user-images.githubusercontent.com/6467633/61269425-1db64a00-a7d1-11e9-8481-5d35877917be.png)

**Comment by karimMourra** [comment]
We do not expose the volume slider in the iOS SDK because the user controls the volume using the iOS Device's volume. What is your use case for wanting a volume slider in the iOS SDK ?

**Comment by colin1994** [comment]
@karimMourra 
We hope video autoplay with sound off. In addition, the user can turn on the sound manually.
So we want to have a volume slider/button for the user to operate.

We now do this by customizing the buttons( player.view.addSubview(muteButton) ), but it's a bit of a hassle and I don't know if there's a better way to do it

**Comment by mbanasiewicz** [comment]
Please expose mute/unmute button at least. Not the full slider but the ability to mute/unmute a player

**Comment by karimMourra** [comment]
@colin1994 and @mbanasiewicz we will soon be adding an addButton api which will allow you to add and remove buttons to the control bar. Will that feature work well for your use case ?

**Comment by karimMourra** [comment]
@colin1994 and @mbanasiewicz the addButton API has been added and it will be available in the next release, 3.10.0
