### ISSUE TITLE
onControlBarVisible was not firing

### ISSUE THREAD

**Issue by colin1994** [jwplayer/JWPlayer-iOS-SDK-cocoapod#42]
Hi,
**onControlBarVisible** callback was not firing when setting player.controls:true
JWPlayer-iOS-SDK version (3.6.0)

Can you help confirm this issue?

Best,
Colin

**Comment by karimMourra** [comment]
Hi @colin1994 setting `player.controls` to `true` will trigger the `onControls` event; `onControlBarVisible` fires when you tap the player and the controls either appear or disappear. Does this answer your concern ? If not, please reopen.

**Comment by colin1994** [comment]
@karimMourra 

Sorry I didn't describe the problem clearly.
 `onControlBarVisible` produces the effect I wanted but it doesn't trigger now.
