### ISSUE TITLE
onControlBarVisible was not firing

### ISSUE THREAD

**Issue by colin1994** [jwplayer/JWPlayer-iOS-SDK-cocoapod#43]
This is a copy of this question: [onControlBarVisible was not firing](https://github.com/jwplayer/JWPlayer-iOS-SDK-cocoapod/issues/42)

@karimMourra 
I cannot re-open this if a repo collaborator closed it. 
But I really hope that you can pay attention to this issue.

When the controls appear or disappear, `onControlBarVisible` is not triggered.
But I need to control the state of my custom view based on this callback.

* JWPlayer-iOS-SDK version (3.6.0)
* iOS 12

Best,
Colin

**Comment by karimMourra** [comment]
hi @colin1994 , I verified that the callback is not firing. I will report this to the Team and will follow up when a release is scheduled. Thank you for bringing this to our concern!

**Comment by karimMourra** [comment]
@colin1994 this is currently being worked on and should ship with 3.6.1 if all goes well.

**Comment by colin1994** [comment]
@karimMourra  Thank you so much. Looking forward to your release.

**Comment by karimMourra** [comment]
@colin1994 SDK version 3.6.1 just went out and includes your fix. Please verify that your issue has been resolved, and if not let us know. Thanks again for reporting this!
