### ISSUE TITLE
Closed Captions Button iOS 13

### ISSUE THREAD

**Issue by matheusfalcao20** [jwplayer/JWPlayer-iOS-SDK-cocoapod#46]
When I updated JWPlayer to version 3.6.3, the Closed Captions button appeared and has no action. How do I hide this button from the interface?

iOS: 13.1.1
Device: iPhone Xr
JWPlayer: 3.6.3

**Comment by karimMourra** [comment]
@matheusfalcao20 could you please share a test stream and test caption files. We have not seen this issue on our end

**Comment by karimMourra** [comment]
Oi @matheusfalcao20 in an effort to increase our response times we will be closing the issues section in this repo. If this is still an issue please reopen this issue in https://github.com/jwplayer/jwplayer-ios-bestPracticeApps
