### ISSUE TITLE
A compiler warning in JWPlayerViewController.h after the 3.7.0 update.

### ISSUE THREAD

**Issue by vahramdodoryan** [jwplayer/JWPlayer-iOS-SDK-cocoapod#47]
Getting a compiler warning in JWPlayerViewController.h after the 3.7.0 update.

<img width="973" alt="Screen Shot 2019-10-09 at 4 14 16 PM" src="https://user-images.githubusercontent.com/2865761/66527133-da0d6c80-eaaf-11e9-9fbd-b2fca3099cbc.png">

Making this change resolves the warning.
<img width="794" alt="Screen Shot 2019-10-09 at 4 16 44 PM" src="https://user-images.githubusercontent.com/2865761/66527248-46886b80-eab0-11e9-92a1-5673f06d9de0.png">

**Comment by david-almaguer** [comment]
I will close this ticket since it was addressed in the 3.8.0 version.
