### ISSUE TITLE
No ability to get the current playlist item from player instance

### ISSUE THREAD

**Issue by dylanjha** [jwplayer/JWPlayer-iOS-SDK-cocoapod#49]
There is no way to get the current playlist item from the player instance.

This feels like an oversight in the iOS sdk. The only way I was able to do this is using a delegate and keep track of it myself.

I tried to log the current playlist item like this:

```obj-c
NSInteger *currentIndex = (long *)self.player.playlistIndex;
NSArray<JWPlaylistItem *> * playlist = self.player.config.playlist;
JWPlaylistItem *playlistItem = [playlist objectAtIndex:(long)currentIndex];
NSLog(@"debug found playlistItem file: %@", playlistItem.file);
```
This works for the initial config, but if another playlistItem is loaded into the player (below) then the above code will not log the current playlist item, it will always log the item from the initial config

```obj-c
JWPlaylistItem * item = [JWPlaylistItem new];
item.file = @"http://qthttp.apple.com.edgesuite.net/1010qwoeiuryfg/sl.m3u8";
[self.player load:@[ item ]];
[self.player play];

// this will always log the initial playlist item
// never the new one that has been loaded
NSInteger *currentIndex = (long *)self.player.playlistIndex;
NSArray<JWPlaylistItem *> * playlist = self.player.config.playlist;
JWPlaylistItem *playlistItem = [playlist objectAtIndex:(long)currentIndex];
NSLog(@"debug found playlistItem file: %@", playlistItem.file);
```

---

I may be missing something here but it feels like the iOS sdk is missing a `getPlaylistItem()` method, [like the one the Javascript SDK has](https://developer.jwplayer.com/jw-player/docs/javascript-api-reference/).

Ideally, if I have an instance of a `JWPlayerController`, it should be able to tell me the current item that is playing.

I created a sample app here that demonstrates the issue: https://github.com/dylanjha/jw-player-ios-sample

**Comment by karimMourra** [comment]
Hi @dylanjha thank you for reporting this! We will add the `getPlaylistItem()` method. 
On a separate note, your workaround should not check the config. The config is meant to be used only for setup; it does not reflect the player's current state. Your workaround also exposes the fact that `getPlaylist()` is missing from the iOS SDK and we will add it as well. After the `load(playlist)` command is called, `getPlaylist()` will return that same playlist.

**Comment by dylanjha** [comment]
@karimMourra that makes sense about the `config`. Thanks for looking into this!

**Comment by askolodny** [comment]
@dylanjha this was added to iOS 3.10.0 which was released yesterday! https://www.jwplayer.com/release-notes/ios-sdk/
