### ISSUE TITLE
How to play the pre-roll Google IMA ads on mute?

### ISSUE THREAD

**Issue by sophie-yang** [jwplayer/JWPlayer-iOS-SDK-cocoapod#50]
Hi,

As the below doc mentions, we couldn't use the volume property of JWPlayerController to control the ads that are played using Google IMA. And we don’t see any settings in **JWAdConfig** or **JWConfig** that can mute the ads. Is there any way to mute the Google IMA ads?
```
This property will have no effect when ads are played using Google IMA, or when casting. Viewers can control volume when casting by changing the device's volume.
```

Here're the code snippets about setting the pre-roll ads:
```Swift
let adBreak = JWAdBreak(tag: adTag, offset: "pre")
let advertising = JWAdConfig()
advertising.client = JWAdClient.googima
advertising.schedule = [adBreak]
config.advertising = advertising

jwPlayerCongtroller = JWPlayerController(config: config, delegate: delegate)
jwPlayerCongtroller.volume = 0.0
```

Here're the SDKs we are using:
```Ruby
# Podfile
pod 'JWPlayer-SDK', '~> 3.9.0'
pod 'GoogleAds-IMA-iOS-SDK', '~> 3.9.2'
```

**Comment by david-almaguer** [comment]
We already addressed this issue in the next release(3.11.0) and it's scheduled for today. Thank you for reporting this @sophie-yang. 👍
