### ISSUE TITLE
 Delay in tab switching with JWPlayerController embemded in one of the tab with SDK 3.9.0

### ISSUE THREAD

**Issue by yb286278** [jwplayer/JWPlayer-iOS-SDK-cocoapod#52]
I have a tab bar which has five controllers, in one of them there is a JWPlayerController embemded to show the remote videos. However, when I upgrade the SDK version from 3.1.2 to 3.9.0, and upon switching the tab to the viewcontroller where the JWPlayer is, there is a obvious delay, it needs to wait like 2-3s before the JWPlayer viewcontroller is actually switched to (can be seen on the screen). Back in SDK 3.1.2, there is no such delay. The codes are the same. I was doubting that the problem comes from the viewWillAppear from the JWPlayerController but I can not make sure since I can only see the header file from the SDK.

**Comment by karimMourra** [comment]
Hi @yb286278  thank you for reporting this. Our team cannot investigate this issue without your implementation; I will need you to report a bug via our [Support Portal](https://support.jwplayer.com/submit-support-case). Select “I have a question for the technical support team” or “I want to report a bug” and then follow the steps to report your issue. Our support team will follow up in a timely manner.

One suggestion is to add the player's view as a subview in `viewDidAppear`.
