### ISSUE TITLE
Compiler warning.

### ISSUE THREAD

**Issue by szcsab** [jwplayer/JWPlayer-iOS-SDK-cocoapod#6]
Hi!

After installing the JWPlayer with cocoapods, I've got a compiler warning.
![screen shot 2017-01-30 at 14 38 33](https://cloud.githubusercontent.com/assets/12250953/22425106/cfeebcb6-e6f9-11e6-8b14-15fcd4b03948.png)

**Comment by RikHeijdens** [comment]
Thanks! We'll fix this in one of the next releases.

**Comment by szcsab** [comment]
Cool, thank you! :)

**Comment by karimJWP** [comment]
@szcsab 2.6.5 was released today, it should address this warning.
