### ISSUE TITLE
#import <JWPlayer-SDK/JWPlayerController.h> In Brigding header causing error

### ISSUE THREAD

**Issue by 3dg2r** [jwplayer/JWPlayer-iOS-SDK-cocoapod#7]
Hi when i do #import on my Bridging Header it cause error "Ambiguous use of 'tag' on my other controllers. Im using tag in buttons.

Please help. 
Im using pods.

**Comment by karimJWP** [comment]
Hi! What version of the SDK are you importing ? Also, is this your first time importing our SDK? Are you able to import different version without any errors ?

**Comment by karimJWP** [comment]
@3dg2r please see my comment above if you haven't yet :)
