### ISSUE TITLE
Playlist play item at index

### ISSUE THREAD

**Issue by eduardo22i** [jwplayer/JWPlayer-iOS-SDK-cocoapod#9]
I try to play a video from the playlist, I'm unable. I tried this which seems to be the only way (for some reason this attribute, playlistIndex, isn't readonly).

`self.player.playlistIndex = currentVideoIndex`
`self.player.play()`

It's incredible that such a basic feature is not available, or I can't find it on the documentation. 
Thanks!

**Comment by karimJWP** [comment]
@eduardo22i we are not seeing issues with the playlistIndex method on our end, could you please file a bug with support+sdk@jwplayer.com ? They will ask you for the streams you are using, the setup code etc and with that information we will be able to properly diagnose. Thank you!

**Comment by vivekgajbe** [comment]
> @eduardo22i we are not seeing issues with the playlistIndex method on our end, could you please file a bug with [support+sdk@jwplayer.com](mailto:support+sdk@jwplayer.com) ? They will ask you for the streams you are using, the setup code etc and with that information we will be able to properly diagnose. Thank you!

I am also fassing same issue , Please let us know if you find any update

**Comment by karimMourra** [comment]
@vivekgajbe please provide test streams and reproduction steps. We are not seeing any issues on our end with this API
